# Generated by Django 2.1.5 on 2019-03-16 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BEMShop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='ServicesModel',
        ),
    ]
