# Generated by Django 2.1.5 on 2019-03-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BEMShop', '0003_auto_20190316_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_description',
            field=models.TextField(),
        ),
    ]
