# Generated by Django 2.1.5 on 2019-03-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BEMShop', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Message',
            field=models.TextField(default='Please enter your message here...', max_length=500),
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='Please enter your subject here...', max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(default='Please enter your name here...', max_length=100),
        ),
    ]
