# Generated by Django 2.1.5 on 2019-03-18 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BEMShop', '0008_auto_20190318_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Message',
            new_name='message',
        ),
    ]
