# Generated by Django 2.1.5 on 2019-03-19 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BEMShop', '0009_auto_20190318_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='service_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='service_title',
            new_name='title',
        ),
    ]
