# Generated by Django 2.1.5 on 2019-03-16 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BEMShop', '0002_auto_20190316_1232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServicesModel',
            new_name='Services',
        ),
    ]
