# Generated by Django 2.1.7 on 2019-03-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BEMShop', '0004_auto_20190327_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Android', 'Android'), ('Iphone', 'Iphone'), ('Accessories', 'Accessories')], max_length=1),
        ),
    ]
